### ISSUE TITLE
[应该不算issue主要是我经验不足]请教部署过程

### ISSUE THREAD

**Issue by freedeaths** [Blackyukun/YuBlog#6]
大概断续试了一周多，还是没有部署成功。我docker和nginx之前简单了解了一下，大体上可以理解，python还相对熟悉一些，uwsgi、mysql和redis是以前完全没有接触过的。想请作者指点一下。

# 按docker-compose的部署方案：

* 我主机Win10 64位，4核16G，虚拟机host only，2CPU4线程，8G，ubuntu 18.04 64bit。python3.6.7, docker 18.09.3, docker-compose 1.23.2。
* 我暂时不打算用证书，所以参考你github上的流程，改nginx的default.conf，server_name 127.0.0.1;
uwsgi_params我没有改
* config.py和.env我暂时都没有改
* 然后sudo docker-compose up -d，再看web的log，从init db这一步开始，就开始不行了，我看了主要错误都是(2003, "Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address)")
* 我按网上提到的，尝试增加过sleep()，也把source/config.ini的CPU和线程数减小过，都没有解决这个问题。现在不知道该如何解决，是我少了哪些步骤吗，可否指教？谢谢
------------------------
之前还按博文里的传统部署试过，htp://127.0.0.1不行，htps://127.0.0.1/admin可以进，但是用户名和密码用默认的都不行T^T(不知道怎么取消超链接，所以少写一t)
另外之前在试的有一次用的apt install的docker-compose，在web的command启动脚本里的$1~$5的参数不对，不过这算是docker-compose的BUG

**Comment by freedeaths** [comment]
我sudo docker exec -it yublog_web_1/bin/bash进入后，写test.py运行，再进入mysql的docker机器，可以看到test.py操作新增的行
```
import pymysql
connection = pymysql.connect(host='172.18.0.3',  # mysql服务器
                             port=3306,
                             user='root',
                             password='password',
                             db='mydb')
# 获取游标
cursor = connection.cursor()
    
# 创建数据表
effect_row = cursor.execute('''
CREATE TABLE `users` (
  `name` varchar(32) NOT NULL,
  `age` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
''')
    
# 插入数据(元组或列表)
effect_row = cursor.execute('INSERT INTO `users` (`name`, `age`) VALUES (%s, %s)', ('mary', 18))
    
# 插入数据(字典)
info = {'name': 'fake', 'age': 15}
effect_row = cursor.execute('INSERT INTO `users` (`name`, `age`) VALUES (%(name)s, %(age)s)', info)
    
connection.commit()

**Comment by freedeaths** [comment]
尝试修改config.py中的62，82，88，94行的IP到对应docker IP后可以打开web了
目前：
1. 用config.py和.env中的ADMIN_LOGIN_NAME和password无法登录
2. config.py中的那些docker IP如何通过docker-compose和web的启动脚本加入到web所在的容器中
谢谢

**Comment by Blackyukun** [comment]
> 尝试修改config.py中的62，82，88，94行的IP到对应docker IP后可以打开web了
> 目前：
> 
> 1. 用config.py和.env中的ADMIN_LOGIN_NAME和password无法登录
> 2. config.py中的那些docker IP如何通过docker-compose和web的启动脚本加入到web所在的容器中
>    谢谢

1. 你可以看 .env 的文件，我后面加了`#` 号是注释用的，而`docker`会将这一行等号后作为值，你可以输入密码 `password  # 管理员登陆密码`试试QAQ~

2. 我们只需要 docker 容器名就好了，不需要记住他的 ip，报 `Can't connect to MySQL server on 'localhost'`的错误，似乎是我忘记把 `config.py` 配置文件 `commit` 了，`DockerConfig()` 类应该有一行Mysql的类属性：

```
class DockerConfig(ProductionConfig):
    SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:password@db:3306/mydb'
    DEBUG = False
    CACHE_REDIS_HOST = 'cache'
```
刚看到这个issue QAQ~

**Comment by Blackyukun** [comment]
如果是上面原因的话，你需要修改 `.env` 文件，把注释换行或者去掉。然后删除`yublog_db_1`容器，还有`mysql/data`文件夹下的文件，然后重启。

**Comment by freedeaths** [comment]
谢谢，我这两天抽空试一下，部署成功了再研究二次开发一下。以前都没有好好玩过，所以细节上有些就要猜和试了，中间还碰到过一些奇怪的问题，后面再整理一下，比如我可以理解web的command里bash -c "./xxx.sh db 3306 root password mydb" 出现过$1是bash $2是-c，也出现过$1是./xxx.sh，$2是db，也出现过$1是db的，主机都是Ubuntu 18.04，后来试验了和docker-compose版本关系也不大，不懂的东西还是太多了，虽然基本差不多能猜出来

**Comment by freedeaths** [comment]
谢谢，已成功进入后台((ง •̀_•́)ง)，居然真的是.env里的注释的关系，我以为这个注释和python里一样不用删的呢。。。多谢了，跑起来以后就可以自己边改边研究了。谢谢，还挺喜欢你这个博客的风格的。我空了在这下面把整个过程中遇到的坑可以再总结一下。

**Comment by freedeaths** [comment]
## 2019-03-19版本状态

我的测试状态不包含SSL证书的使用。
目前，按README“推荐docker-compose部署”部分的说明文字，已经**几乎**可以做到“按图施工”的状态了。

1. 配置default.conf;
2. 配置.env和config.py；
3. **sudo chmod 777 ./source/docker-entrypoint.sh** (在我的非ROOT用户测试环境中必须给权限，否则web无法启动)
4. sudo docker-compose up -d

## 使用协议

关于这一点想请教一下作者，目前这个基于哪种开源协议呢？以后研究学习后如果修改或者二次开发，是Fork了自由发挥？还是给你这边PR呢？直接给你这边PR可能也不太合适吧，因为有些可能也不在你的规划之内。
另外作者的计划之类的活儿，有哪些是可以分给感兴趣的人做的吗？

## 之前遇到的问题请教

主要原因是我非专业出身，docker/nginx/python自己学习过一点，但是没有实战经验，mysql/redis/flask/uwsgi在此之前是完全没有接触过。基于以上原因，在近两周的部署过程中，有一些问题想请教。
1. 我查了docker-compose的文档，知道service name会返回容器IP，但是我并不是很清楚它的作用域，是只在docker-compose的编排启动过程起作用，还是在这些容器运行的生命周期中都起作用呢？我尝试过在启动脚本docker-entrypoint.sh中echo $1，显示也就是db并不是IP，然后如果在python中也无法print(db)，那在web容器中如何可以显式地查看到db和redis的IP信息呢？
2. 在数次不同尝试中，关于docker-compose.yml中的command: bash -c "./docker-entrypoint.sh db 3306 root ${MYSQL_PASSWORD} mydb"以及docker-entrypoint.sh中的python wait_for_db.py $1 $2 $3 $4 $5，我得到过三次不同的结果，第一次是$1=bash, $2=-c, $3 ="./docker-entrypoint.sh db 3306 root ${MYSQL_PASSWORD} mydb", $4=NULL, $5=NULL；第二次是$1=./docker-entrypoint.sh, $2=db, $3 =3306, $4=root, $5=${MYSQL_PASSWORD}；第三次是正确的需求的。我不是特别明白为什么会出现不同的情况，之前我以为是docker-compose的版本问题，但后来发现并不是，但是测试环境我也不是记得特别清了，可能现在也复现不了，主要还是对shell脚本和传递变量不太熟悉的原因。另外，command: bash -c "./docker-entrypoint.sh db 3306 root ${MYSQL_PASSWORD} mydb"和command: ./docker-entrypoint.sh db 3306 root ${MYSQL_PASSWORD} mydb有区别吗？是bash和dash的区别？
3. 关于数据库的各种问题，这个BUG作者刚刚修复（不过不是我的PR呀(╯°Д°)╯︵ ┻━┻），因为这块以前完全没弄过，所以就自己学习了，中间主要是2003的错误，还有一些别的是在用非docker-compose的方式部署的时候碰到的。
4. 关于redis的问题。目前还没有深入看博客的代码，但是我grep了一下“redis”，发现并没有几行相关的内容，在docker-compose里也没看到有啥特别的配置。这货不需要配置的吗(＃°Д°)

其它的，想到再说吧，还是以Issue的形式吗？作者自己的博客里邮箱的加密方式我倒还真是没有猜出来，试过几种都不对，然后在部署过程中看到了至少两个邮箱，不知道是否能联系到，嘿嘿

**Comment by Blackyukun** [comment]
这只是自己写的小项目，fork可以自由发挥。`另外作者的计划之类的活儿，有哪些是可以分给感兴趣的人做的吗？`这个暂时没有。

文字写的太多了，自己使用搜索引擎吧。

我在博客里留的邮箱加密方式不用猜了，就是普通的base64转码。

**Comment by freedeaths** [comment]
因为是email的古老加密方式，我第一个猜的就是Base64，然并卵╮(╯-╰)╭
我还是比较遵守提问的智慧的，之前肯定还是有google过的，不过没事，我自己解决吧，谢谢
那我就fork了自由发挥了，然后时不时地再来看看有什么好的feature
谢谢了。Issue可以关了:)
