### ISSUE TITLE
[BUG]修改MYSQL密码后部署出现1045错误

### ISSUE THREAD

**Issue by freedeaths** [Blackyukun/YuBlog#7]
原因为
./source/config.py
line 122:
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:password@db:3306/mydb'
这里传入的是password
应改为
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:{password}@db:3306/mydb'.format(
        password=Config.MYSQL_PASSWORD)

**Comment by Blackyukun** [comment]
多谢提醒，以修改

**Comment by freedeaths** [comment]
我不是IT行业出身，只是凭着个人爱好在学习，工作忙，进展比较慢。如果不介意的话，我非常乐意多向你们学习，也想把你这个博客的全栈搞明白，甚至做出一些贡献。目前刚好数据库等方面还有很多疑问，希望多向你学习。
Github没法私信，要不你先加我不常用的微信，备注下YuBlog，然后我从小号再推给我常用的微信吧。加完麻烦把我这条评论删除。谢谢。
微信号：Friehof
